/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProcessualCivilRouteImport } from './routes/processual-civil'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as MediacaoArbitragemRouteImport } from './routes/mediacao-arbitragem'
import { Route as DireitoTrabalhistaRouteImport } from './routes/direito-trabalhista'
import { Route as DireitoCivilRouteImport } from './routes/direito-civil'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConsultoriaEmpresarialRouteImport } from './routes/consultoria-empresarial'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AgronegocioRouteImport } from './routes/agronegocio'
import { Route as IndexRouteImport } from './routes/index'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessualCivilRoute = ProcessualCivilRouteImport.update({
  id: '/processual-civil',
  path: '/processual-civil',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MediacaoArbitragemRoute = MediacaoArbitragemRouteImport.update({
  id: '/mediacao-arbitragem',
  path: '/mediacao-arbitragem',
  getParentRoute: () => rootRouteImport,
} as any)
const DireitoTrabalhistaRoute = DireitoTrabalhistaRouteImport.update({
  id: '/direito-trabalhista',
  path: '/direito-trabalhista',
  getParentRoute: () => rootRouteImport,
} as any)
const DireitoCivilRoute = DireitoCivilRouteImport.update({
  id: '/direito-civil',
  path: '/direito-civil',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultoriaEmpresarialRoute = ConsultoriaEmpresarialRouteImport.update({
  id: '/consultoria-empresarial',
  path: '/consultoria-empresarial',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AgronegocioRoute = AgronegocioRouteImport.update({
  id: '/agronegocio',
  path: '/agronegocio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agronegocio': typeof AgronegocioRoute
  '/blog': typeof BlogRoute
  '/consultoria-empresarial': typeof ConsultoriaEmpresarialRoute
  '/contato': typeof ContatoRoute
  '/direito-civil': typeof DireitoCivilRoute
  '/direito-trabalhista': typeof DireitoTrabalhistaRoute
  '/mediacao-arbitragem': typeof MediacaoArbitragemRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/processual-civil': typeof ProcessualCivilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agronegocio': typeof AgronegocioRoute
  '/blog': typeof BlogRoute
  '/consultoria-empresarial': typeof ConsultoriaEmpresarialRoute
  '/contato': typeof ContatoRoute
  '/direito-civil': typeof DireitoCivilRoute
  '/direito-trabalhista': typeof DireitoTrabalhistaRoute
  '/mediacao-arbitragem': typeof MediacaoArbitragemRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/processual-civil': typeof ProcessualCivilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agronegocio': typeof AgronegocioRoute
  '/blog': typeof BlogRoute
  '/consultoria-empresarial': typeof ConsultoriaEmpresarialRoute
  '/contato': typeof ContatoRoute
  '/direito-civil': typeof DireitoCivilRoute
  '/direito-trabalhista': typeof DireitoTrabalhistaRoute
  '/mediacao-arbitragem': typeof MediacaoArbitragemRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/processual-civil': typeof ProcessualCivilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agronegocio'
    | '/blog'
    | '/consultoria-empresarial'
    | '/contato'
    | '/direito-civil'
    | '/direito-trabalhista'
    | '/mediacao-arbitragem'
    | '/politica-de-privacidade'
    | '/processual-civil'
    | '/sitemap.xml'
    | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agronegocio'
    | '/blog'
    | '/consultoria-empresarial'
    | '/contato'
    | '/direito-civil'
    | '/direito-trabalhista'
    | '/mediacao-arbitragem'
    | '/politica-de-privacidade'
    | '/processual-civil'
    | '/sitemap.xml'
    | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/agronegocio'
    | '/blog'
    | '/consultoria-empresarial'
    | '/contato'
    | '/direito-civil'
    | '/direito-trabalhista'
    | '/mediacao-arbitragem'
    | '/politica-de-privacidade'
    | '/processual-civil'
    | '/sitemap.xml'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgronegocioRoute: typeof AgronegocioRoute
  BlogRoute: typeof BlogRoute
  ConsultoriaEmpresarialRoute: typeof ConsultoriaEmpresarialRoute
  ContatoRoute: typeof ContatoRoute
  DireitoCivilRoute: typeof DireitoCivilRoute
  DireitoTrabalhistaRoute: typeof DireitoTrabalhistaRoute
  MediacaoArbitragemRoute: typeof MediacaoArbitragemRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  ProcessualCivilRoute: typeof ProcessualCivilRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processual-civil': {
      id: '/processual-civil'
      path: '/processual-civil'
      fullPath: '/processual-civil'
      preLoaderRoute: typeof ProcessualCivilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mediacao-arbitragem': {
      id: '/mediacao-arbitragem'
      path: '/mediacao-arbitragem'
      fullPath: '/mediacao-arbitragem'
      preLoaderRoute: typeof MediacaoArbitragemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direito-trabalhista': {
      id: '/direito-trabalhista'
      path: '/direito-trabalhista'
      fullPath: '/direito-trabalhista'
      preLoaderRoute: typeof DireitoTrabalhistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direito-civil': {
      id: '/direito-civil'
      path: '/direito-civil'
      fullPath: '/direito-civil'
      preLoaderRoute: typeof DireitoCivilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultoria-empresarial': {
      id: '/consultoria-empresarial'
      path: '/consultoria-empresarial'
      fullPath: '/consultoria-empresarial'
      preLoaderRoute: typeof ConsultoriaEmpresarialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agronegocio': {
      id: '/agronegocio'
      path: '/agronegocio'
      fullPath: '/agronegocio'
      preLoaderRoute: typeof AgronegocioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgronegocioRoute: AgronegocioRoute,
  BlogRoute: BlogRoute,
  ConsultoriaEmpresarialRoute: ConsultoriaEmpresarialRoute,
  ContatoRoute: ContatoRoute,
  DireitoCivilRoute: DireitoCivilRoute,
  DireitoTrabalhistaRoute: DireitoTrabalhistaRoute,
  MediacaoArbitragemRoute: MediacaoArbitragemRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  ProcessualCivilRoute: ProcessualCivilRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
